//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResEstateDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResEstateDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResEstateDetail", typeof(GlobalResEstateDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambah Data Baru.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kembali.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adakah anda pasti untuk menghapuskan maklumat berikut?.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Acc.
        /// </summary>
        public static string hdrAcc {
            get {
                return ResourceManager.GetString("hdrAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tindakan.
        /// </summary>
        public static string hdrAction {
            get {
                return ResourceManager.GetString("hdrAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Aktiviti.
        /// </summary>
        public static string hdrActvtCode {
            get {
                return ResourceManager.GetString("hdrActvtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CIT.
        /// </summary>
        public static string hdrCIT {
            get {
                return ResourceManager.GetString("hdrCIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Ladang.
        /// </summary>
        public static string hdrCode {
            get {
                return ResourceManager.GetString("hdrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centre.
        /// </summary>
        public static string hdrCostCentre {
            get {
                return ResourceManager.GetString("hdrCostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string hdrDebit {
            get {
                return ResourceManager.GetString("hdrDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potongan.
        /// </summary>
        public static string hdrDeduction {
            get {
                return ResourceManager.GetString("hdrDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendapatan.
        /// </summary>
        public static string hdrEarning {
            get {
                return ResourceManager.GetString("hdrEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emel Ladang.
        /// </summary>
        public static string hdrEmail {
            get {
                return ResourceManager.GetString("hdrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP (P).
        /// </summary>
        public static string hdrEmployeeKwsp {
            get {
                return ResourceManager.GetString("hdrEmployeeKwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCSO (P).
        /// </summary>
        public static string hdrEmployeeSocso {
            get {
                return ResourceManager.GetString("hdrEmployeeSocso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP (M).
        /// </summary>
        public static string hdrEmployerKwsp {
            get {
                return ResourceManager.GetString("hdrEmployerKwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCSO (M).
        /// </summary>
        public static string hdrEmployerSocso {
            get {
                return ResourceManager.GetString("hdrEmployerSocso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagi Bulan.
        /// </summary>
        public static string hdrForMonth {
            get {
                return ResourceManager.GetString("hdrForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GL.
        /// </summary>
        public static string hdrGL {
            get {
                return ResourceManager.GetString("hdrGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaji Kasar.
        /// </summary>
        public static string hdrGrossSalary {
            get {
                return ResourceManager.GetString("hdrGrossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit.
        /// </summary>
        public static string hdrKredit {
            get {
                return ResourceManager.GetString("hdrKredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Ladang.
        /// </summary>
        public static string hdrName {
            get {
                return ResourceManager.GetString("hdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No KP / Passport.
        /// </summary>
        public static string hdrNoKp {
            get {
                return ResourceManager.GetString("hdrNoKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Pekerja.
        /// </summary>
        public static string hdrNoPkj {
            get {
                return ResourceManager.GetString("hdrNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catitan.
        /// </summary>
        public static string hdrNote {
            get {
                return ResourceManager.GetString("hdrNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah ID.
        /// </summary>
        public static string hdrWlyhid {
            get {
                return ResourceManager.GetString("hdrWlyhid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string lblCompanyNo {
            get {
                return ResourceManager.GetString("lblCompanyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumbangan Majikan.
        /// </summary>
        public static string lblEmployerContribution {
            get {
                return ResourceManager.GetString("lblEmployerContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblEstateName {
            get {
                return ResourceManager.GetString("lblEstateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Bersih.
        /// </summary>
        public static string lblNetTotal {
            get {
                return ResourceManager.GetString("lblNetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Akaun.
        /// </summary>
        public static string lblNoAcc {
            get {
                return ResourceManager.GetString("lblNoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potongan Lain-lain.
        /// </summary>
        public static string lblOthersDeduction {
            get {
                return ResourceManager.GetString("lblOthersDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendapatan Lain-lain.
        /// </summary>
        public static string lblOthersEarning {
            get {
                return ResourceManager.GetString("lblOthersEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laporan Paysheet.
        /// </summary>
        public static string lblPaysheetReport {
            get {
                return ResourceManager.GetString("lblPaysheetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penambahan Data Baru.
        /// </summary>
        public static string lblTitleCreate {
            get {
                return ResourceManager.GetString("lblTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus Data.
        /// </summary>
        public static string lblTitleDelete {
            get {
                return ResourceManager.GetString("lblTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kemaskini Data.
        /// </summary>
        public static string lblTitleUpdate {
            get {
                return ResourceManager.GetString("lblTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Potongan.
        /// </summary>
        public static string lblTotalDeduction {
            get {
                return ResourceManager.GetString("lblTotalDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Pendapatan.
        /// </summary>
        public static string lblTotalEarning {
            get {
                return ResourceManager.GetString("lblTotalEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laporan Senarai Transaksi.
        /// </summary>
        public static string lblTransactionListingReport {
            get {
                return ResourceManager.GetString("lblTransactionListingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jadual Aktiviti Kerja.
        /// </summary>
        public static string lblWorkerAktvt {
            get {
                return ResourceManager.GetString("lblWorkerAktvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tandatangan Pekerja.
        /// </summary>
        public static string lblWorkerSign {
            get {
                return ResourceManager.GetString("lblWorkerSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem Tergendala.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiada Rekod.
        /// </summary>
        public static string msgNoRecord {
            get {
                return ResourceManager.GetString("msgNoRecord", resourceCulture);
            }
        }
    }
}
